name: coinforbarter_sdk
description: This is a simple SDK that allows you to integrate a cryptocurrency payment gateway in your flutter project.
homepage: https://github.com/fiizzy/coinforbarter_sdk_flutter_V1.0.0
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_countdown_timer: ^4.1.0
  get: ^4.5.1
  http: ^0.13.4
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Manrope-Light
      fonts:
        - asset: fonts/Manrope-Light.ttf

    - family: Manrope-Regular
      fonts:
        - asset: fonts/Manrope-Regular.ttf

    - family: Manrope-Medium
      fonts:
        - asset: fonts/Manrope-Medium.ttf

    - family: Manrope-Bold
      fonts:
        - asset: fonts/Manrope-Bold.ttf

    - family: Manrope-e=ExtraBold
      fonts:
        - asset: fonts/Manrope-ExtraBold.ttf
